### ISSUE TITLE
new pypi release

### ISSUE THREAD

**Issue by gurer-kensho** [messense/rjsonnet-py#4]
Thank you very much for this amazing product!

Would you mind pushing a new release to pypi with the current jrsonnet master as there are some fixes related to argument default values which would be nice to have without a custom build?

**Comment by messense** [comment]
Port the code to current jrsonnet master branch takes time, there are lots of breaking changes, help appreciated if you are up to the task!

**Comment by gurer-kensho** [comment]
Are you talking about the breaking-refactors branch? I might try to help in my free time. But right now the fix I'm talking about was in the current jrsonnet master branch. When I clone your project and do a pip install it builds without any problem. It should be straightforward to re-build and push new wheels as something like 0.4.5 to pypi.

**Comment by messense** [comment]
No, I'm talking about the current master branch, `rjsonnet-py` main branch compiling fine because it's pinned to an [old revision of jrsonnet](https://github.com/CertainLach/jrsonnet/commit/e1fb5e1edb6f4935484bb3073564c8808e7fafac), I'm not sure if it will fix your issue.

**Comment by gurer-kensho** [comment]
Ah, I just noticed the cargo.lock file. That is really weird. I found my fix in https://github.com/CertainLach/jrsonnet/commit/b5434962bef6001feb2207490ba12ddc58ca1623 which should have been in the release.

I have
```
$ pip freeze|grep rjsonnet
rjsonnet==0.4.4
$ python
Python 3.8.13 (default, Sep 14 2022, 15:31:33) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
>>> import rjsonnet
>>> rjsonnet.__version__
'0.4.4'
```

in two virtual envs. The one which was installed with pip install rjsonnet is giving me
```
RuntimeError: variable is not defined: a
```
whereas one I did a pip install . from your git clone is working like the official jsonnet:
```
3
```

for the code
```
local x = function (a, b=a+1) a+b;

x(1)
```

**Comment by messense** [comment]
v0.4.5 is out: https://pypi.org/project/rjsonnet/0.4.5/

**Comment by gurer-kensho** [comment]
Thank you very much!

Now everything works with a clean pip install from pypi.

**Comment by messense** [comment]
> Port the code to current jrsonnet master branch takes time, there are lots of breaking changes

Done in https://github.com/messense/rjsonnet-py/pull/7
